---
title: "R 语言初探之数据结构"
output: html_document
---

## 向量

R 里面的向量看起来像 Python 的 list，但又不是 list，更像是Python 里一维的数组。

**向量入门**

基础
```{r,collapse=TRUE,comment='#>'}
vec <- c(1, 2, 3, 6, 5, 4)
vec[c(1, 2, 4)]
class(vec)
vec[1:2] # 末尾包含
```

Python 代码,除了用列表推导式之外还可以直接用 Numpy 实现
```{r engine='python',echo=TRUE}
import numpy as np
a= np.array([1, 2, 3, 6, 5, 4])
print a[[0, 1, 3]]
print type(a)
```

创建向量 类 Python range
```{r,collapse=TRUE,comment='#>'}
a <- seq(10)
a
b <- seq(10, 13)
b
temp <- c(1, 2, 4, 0)
temp * b
```

生成有规律的向量， 类 np.linspace
```{r,collapse=TRUE,comment='#>'}
vec <- seq(1, 100, length.out = 10) # 还有个long参数也非常有用。
vec
vec[-4] #这点跟 Python 很不一样

seq(from=2, to=1000, length.out = 10)
seq(from=2, to=1000, length=10)

group1 <- rep(1:3, times = c(8, 10, 9))
group2 <- factor(group1) # 转换成因子
group1
class(group1)
class(group2)
length(group1) # as Py len
```

随机向量
```{r,collapse=TRUE,comment='#>'}
vec_random1 <- runif(5) # 0-1
vec_random1
vec_random2 <- sample(c('A', 'B'), size = 10, replace = TRUE) # 随机字符向量
vec_random2
vector1 <- numeric(10)
vector1 # empty vector
```

逻辑判断
```{r,collapse=TRUE,comment='#>'}
temp[1:3]
temp[c(TRUE, TRUE, FALSE, FALSE)]
temp[temp > 1]
```


## 矩阵
矩阵是二维的容器，可包含数值、逻辑、字符等数据

生成矩阵
```{r,collapse=TRUE,comment='#>'}
vector <- 1:12
class(vector)
my_matrix <- matrix(vector, nrow = 3, ncol = 4, byrow = FALSE)
dim(my_matrix)
vector
my_matrix

vector1 <- vector2 <- vector3 <- runif(3)
my_matrix <- cbind(vector1, vector2, vector3) # 一致的向量类型进行合并
my_matrix
round(my_matrix*10, digits = 2) # 取2位
```

取子集和计算
```{r,collapse=TRUE,comment='#>'}
my_mat <- matrix(c(8, 3, 4, 1, 5, 9, 6, 7, 2), ncol = 3)
print(my_mat)

my_mat[1,1] + my_mat[1, 2] + my_mat[1,3]
sum(my_mat[1,])
rowSums(my_mat)
colSums(my_mat)
sum(diag(my_mat))

class(my_mat[1,]) # 退化成向量了
my_mat[1, , drop=FALSE] # 保留矩阵属性
my_mat[my_mat <= 5] <- 0 # 改变赋值
my_mat

# ifelse 函数
my_mat <- matrix(c(8, 3, 4, 1, 5, 9, 6, 7, 2), ncol = 3)
ifelse(my_mat > 0.5, 1, 0)
```

## 数据框

优点在于不同向量的数据类型可以不一样，但各列的长度必须一致

```{r,collapse=TRUE,comment='#>'}
city <- c('A', 'B', 'C', 'D')
temp <- c(27, 29, 23, 14)
data <- data.frame(city, temp) # 对于 list，Py 不能直接这么导，会把整数向量变为索引，得用 dir 的方式
data
data[, 1] # Py data.ix[:,0] | data.iloc[:,0]
data$temp
class(data$city) # 本是字符，自动转了因子，若不想转，课用 stringAsFactors = FALSE 设定
```

组合索引
```{r,collapse=TRUE,comment='#>'}
data[data$temp > mean(data$temp), ]
# data['temp', ] # empty，这是提取行的语法
data[, 'city'] # 提取列
data$temp > mean(data$temp)
with(data, data[temp > mean(temp), ]) # 直接操作列名,省略 $
with(data, data[temp > mean(temp), 'city']) 
```

熟悉数据框最快的办法
```{r,collapse=TRUE,comment='#>'}
summary(data) # as Py describe
dim(data) # as Py data.shape
head(data) # 看前6行
#data.head(1) # 不能这么干
head(data, n = 1L)
str(data) # 返回数据结构
```

数据框的排序
```{r,collapse=TRUE,comment='#>'}
order(data$temp) # 返回数据的索引号
data[order(data$temp), ]
data[order(data$temp, decreasing = T), ][1:2, ] # 反序
```

## 列表
```{r,collapse=TRUE,comment='#>'}
data_list <- list(temp = temp, city = city)
print(data_list)

data_list$mat <- my_mat
data_list$data <- data
names(data_list)
class(data_list[3])
data_list[3]
data_list[[3]] # 没有 name
class(data_list[[3]])
```

## 特殊对象

缺失值和空值
```{r,collapse=TRUE,comment='#>'}
temp <- c(27, 29, 23, 14, NA)
mean(temp)
mean(temp, na.rm = TRUE)
temp <- c(27, 29, 23, 14, NULL)
data_list <- NULL # 快速删除一列
mean(temp) # TRUE
```

连接
```{r,collapse=TRUE,comment='#>'}
textcon = textConnection('output', 'w')
sink(textcon) # 开
x <- runif(10)
summary(x)
print('这话不显示了，写入了 output 对象了')
sink() # 关闭控制台转换
print(output)

showConnections()
class(textcon)
close(textcon)
```

公式
```{r,collapse=TRUE,comment='#>'}
n <- 1:50
xvar <- paste0('x', n )
right <- paste(xvar, collapse = ' + ')
left <- 'y~'
my_formula <- paste(left, right)
my_formula <- as.formula(my_formula)
class(my_formula)

left
```

表达式
```{r,collapse=TRUE,comment='#>'}
ex <- expression(x <- seq(1, 10, 2))
print(ex)
class(ex)
eval(ex)
print(x)

tex <- c('z<-seq(1, 10, 2)', 'print(z)' )
eval(parse(text = tex))
```

环境变量
```{r,collapse=TRUE,comment='#>'}
ls()
env1 <- new.env()

assign("x1", 1:5, envir = env1)
ls(envir = env1)
get('x1', envir = env1) # 为啥没法直接用 x1 取呢？

exists('x1', envir = env1)
rm('x1', envir = env1)
```

函数
```{r,collapse=TRUE,comment='#>'}
exp(1)

myfunc <- function(r){
  area <- pi*r^2
  return(area)
} # 内部可以调用 global value
print(myfunc(4)) 

myfunc
```


